### PR TITLE
ci: use latest cloudflare deploy

### PR DESCRIPTION
**Pull request by rndquu**
Resolves https://github.com/pavlovcik/uad.ubq.fi/pull/2#issuecomment-2002474052

Don't forget to set the following github repo secrets:
- [CLOUDFLARE_ACCOUNT_ID](https://github.com/pavlovcik/uad.ubq.fi/blob/84a98077007c56fbf823d387ff176c0591b84b40/.github/workflows/deploy.yml#L23)
- [CLOUDFLARE_API_TOKEN](https://github.com/pavlovcik/uad.ubq.fi/blob/84a98077007c56fbf823d387ff176c0591b84b40/.github/workflows/deploy.yml#L24)

### CODE REVIEW

**Comment by 0x4007** [comment]
I just updated the secrets, hopefully with the correct permissions on the key, but unsure how to test. I just re-ran build and don't see the deploy.

Working on re-running this one https://github.com/pavlovcik/uad.ubq.fi/actions/runs/8364594127

**Comment by rndquu** [comment]
> I just updated the secrets, hopefully with the correct permissions on the key, but unsure how to test. I just re-ran build and don't see the deploy.
> 
> Working on re-running this one https://github.com/pavlovcik/uad.ubq.fi/actions/runs/8364594127

Merge this PR first

**Comment by 0x4007** [comment]
- Looks suspicious https://github.com/pavlovcik/uad.ubq.fi/actions/runs/8369453127/job/22915216177#step:2:369
   - I understand that I did not add `ubiquibot-continuous-deploys` to my repository here.  
- Looks good https://github.com/pavlovcik/uad.ubq.fi/actions/runs/8369453127/job/22915216177#step:2:416

**Comment by rndquu** [comment]
> I understand that I did not add ubiquibot-continuous-deploys to my repository here.

👍

**Comment by rndquu** [comment]
I don't think deployment URLs will be posted in comments since installation id is [hardcoded](https://github.com/ubiquity/cloudflare-deploy-action/blob/05cf678961b481e76c21b95679c17ec9d3b33c23/auth/installation-id) for `ubiquity` org so even if you manage to install `ubiquibot-continuous-deploys` here then you'll need to use another installation id (for https://github.com/pavlovcik)

**Comment by 0x4007** [comment]
No problem. This is a temporary repository until we redo the deploy and UI.

**Pull request merged**
