### PR TITLE
upgrade rpc logic

### PR DESCRIPTION
**Pull request by Keyrxng**
Relates to https://github.com/pavlovcik/uad.ubq.fi/pull/2

- bumped next to v14 as it was throwing errors with how it was handling the esm package
- upgraded the rpc logic to use `rpc-handler`

##### ignore the background handler calls I just swapped out the providers for QA
use_provider_handling_w_background_handler_calls

##### works as expected but does require multi dynamic import (which I now see the fix for shortening the rpc-handler import path by exporting one file that handles multi-import like the way the hook does here)
rpc_handler_handling

### CODE REVIEW

**Comment by Keyrxng** [comment]
@pavlovcik just the finishing touches I was working on for the other PR

**Comment by 0x4007** [comment]
I can't really tell the difference when I run this. Whats the purpose of this in the scope of getting the new RPCs working? What was the problem with the original deliverable?

**Comment by Keyrxng** [comment]
In essence nothing other than now it's not one singular websocket endpoint being used when not MM connected. 

The UI is still using the MM provider for the most part but thought it prudent to upgrade the RPC logic here too seeing as it's happening across the board

**Comment by 0x4007** [comment]
It seems like there's a lot of out of scope changes to the react code. They should be done in a separate pull

**Comment by Keyrxng** [comment]
> It seems like there's a lot of out of scope changes to the react code. They should be done in a separate pull

- [69493c4](https://github.com/pavlovcik/uad.ubq.fi/pull/3/commits/69493c49cae2164fd6fc4c5cf0b4f0a1e4dcc40b) this is required as `Nextjs@14` handles `<a>` inside `<Link>` and `Nextjs@14` is required as it was a blocker for the `rpc-handler` package, removing `<a>` is the only change

- [cb01d94](https://github.com/pavlovcik/uad.ubq.fi/pull/3/commits/cb01d94c5912aaba4fce1457316a6bdf444ca7dc) using `useMemo` here prevents re-initialized of the provider state once it's already set unless one of the values change

I'll open a new PR with the `useMemo` stuff

**Comment by Keyrxng** [comment]
It shaves about 1-1.5 secs off of the loading time memo-izing (i mean the time it takes for the APR to display)

**Comment by Keyrxng** [comment]
- https://github.com/pavlovcik/uad.ubq.fi/actions/runs/8362711273/job/22893960729?pr=3

`next build` passing but `deploy to cloudflare` is failing

**Comment by Keyrxng** [comment]
@0x4007 the trouble with this is that `useWeb3` is called all throughout the codebase meaning that it's receiving a different provider for various parts of the code and because without https://github.com/ubiquity/rpc-handler/pull/24 the providers are still susceptible to potential call failure.

So this would benefit from `rpc-handler` returning a proxy and would benefit from memo-izing the `web3State` so that it prevents it re-rendering multiple providers and drops the external calls made.

<hr/>

Having said that, on the prod instance right now I can repro a bunch of call failures just by accessing credits.

image

**Comment by 0x4007** [comment]
Oh I'm surprised you are working on this codebase. I almost think we should toss it out and start fresh. Anyways if you are making a lot of changes, consider doing it across several tightly scoped pulls.

**Comment by Keyrxng** [comment]
> Oh I'm surprised you are working on this codebase. I almost think we should toss it out and start fresh. Anyways if you are making a lot of changes, consider doing it across several tightly scoped pulls.

https://github.com/ubiquity/.github/issues/100#issuecomment-2168719952 

This is the last place I believe that `rpc-handler` was to be implemented

<hr/>

Other than memo-izing these are the only changes needed as a proxied provider will handle retry etc. I removed the dirty commits I made memo-izing in this PR previously so it's cleaner

<del>Noticed audit does use hardcoded RPCs, will do that now.</del>

The RPCs are not used in audit, neither of the two functions which use `RPC_URLS` are called anywhere.

**Comment by 0x4007** [comment]
I am surprised that audit isn't using RPCs. @rndquu rfc

**Comment by Keyrxng** [comment]
as far as I can tell audit is relying on the DB having all of the data needed other than what can be taken directly from parsing the repo. 

Because of this [issue](https://github.com/ubiquity/audit.ubq.fi/issues/12) I adjusted `airdrop-cli` so that, as best I could, match up permits to their corresponding repo, issue number with the tx hash which I thought would make life a bit easier and certainly would for `audit` if the `locations` table is due to be removed.

**Review by 0x4007 — APPROVED** [review]

**Comment by rndquu** [comment]
> I am surprised that audit isn't using RPCs. @rndquu rfc

> as far as I can tell audit is relying on the DB

Yes, https://github.com/ubiquity/audit.ubq.fi relies on a DB right now since all permits (at least in bot v2) are saved in a DB right now and it's easier to fetch them from a DB instead of parsing etherscan/github/etc... Besides there's an ongoing [task](https://github.com/ubiquity/.github/issues/109) to save already generated (i.e. old) permits to a DB to make the `permits` table "whole".

**Pull request merged**
